- type: entity
  save: false
  id: BaseSpeciesPickupable
  abstract: true
  components:
  - type: Item
    size: Huge
    shape:
    - 0,0,4,3
  - type: NestingMob
  - type: MultiHandedItem
  - type: CanEscapeInventory
    baseResistTime: 3
