- type: roleLoadout
  id: LustSunriseJobMedicalDoctor
  groups:
  - SunriseMedicalDoctorHead
  - MedicalEyewear
  - SunriseMedicalMask
  - SunriseMedicalDoctorNeck
  - MedicalDoctorJumpsuit
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalGloves
  - SunriseMedicalShoes
  - GroupTankHarness
  - MedicalBackpack
  - SunriseMedicalDoctorPDA
  - SunriseSurvivalMedical
  - GroupSpeciesBreathToolMedical
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - MedicalDoctorJobTrinkets
  - MedicalTrinkets
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustSunriseJobMedicalIntern
  groups:
  - SunriseMedicalDoctorHead
  - MedicalEyewear
  - SunriseMedicalMask
  - SunriseMedicalDoctorNeck
  - MedicalInternJumpsuit
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalGloves
  - SunriseMedicalShoes
  - GroupTankHarness
  - MedicalBackpack
  - SunriseSurvivalMedical
  - GroupSpeciesBreathToolMedical
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - MedicalInternJobTrinkets
  - MedicalTrinkets
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustSunriseJobChemist
  groups:
  - SunriseChemistHead
  - SunriseChemistMask
  - SunriseChemistNeck
  - ChemistJumpsuit
  - SunriseChemistOuterClothing
  - SunriseChemistGloves
  - SunriseChemistShoes
  - GroupTankHarness
  - ChemistBackpack
  - SunriseChemistMisc
  - SunriseSurvivalMedical
  - GroupSpeciesBreathToolMedical
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - ChemistJobTrinkets
  - MedicalTrinkets
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustSunriseJobParamedic
  groups:
  - SunriseParamedicHead
  - MedicalEyewear
  - SunriseParamedicMask
  - SunriseParamedicNeck
  - ParamedicJumpsuit
  - SunriseParamedicOuterClothing
  - SunriseParamedicGloves
  - SunriseParamedicShoes
  - GroupTankHarness
  - MedicalBackpack
  - SunriseSurvivalMedical
  - GroupSpeciesBreathToolMedical
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - ParamedicJobTrinkets
  - MedicalTrinkets
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustJobSeniorPhysician
  groups:
  - SeniorPhysicianHead
  - SunriseGlasses
  - SeniorPhysicianMask
  - SeniorPhysicianNeck
  - SeniorPhysicianJumpsuit
  - SeniorPhysicianOuterClothing
  - SeniorPhysicianGloves
  - MedicalBackpack
  - SeniorPhysicianBelt
  - SeniorPhysicianShoes
  - SurvivalMedical
  - SunriseTrinkets
  - MedicalTrinkets
  - GroupSpeciesBreathTool
  - Bra
  - Pants
  - Socks
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustJobMedicalPathologist
  groups:
  - PathologistHead
  - SunriseGlasses
  - PathologistMask
  - PathologistNeck
  - MedicalDoctorJumpsuit
  - PathologistOuterClothing
  - PathologistGloves
  - PathologistShoes
  - MedicalBackpack
  - GroupTankHarness
  - SurvivalMedical
  - SunriseTrinkets
  - MedicalTrinkets
  - GroupSpeciesBreathToolMedical
  - Bra
  - Pants
  - Socks
  - SpecialLoadout
  - Contributors

