- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 #4 hrs # Sunrise-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 36000 # 15 hrs # Sunrise-RoleTime
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  canBeAntag: false # Sunrise-Edit
  supervisors: job-supervisors-cmo
  displayWeight: 25  # Sunrise
  access:
  - Medical
  - Maintenance
  - External # Sunrise-Add
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
    eyes: ClothingEyesHudMedical # Sunrise-Edit
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
    - HandheldCrewMonitor # Sunrise-Edit

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
