language: ru-RU

reviews:
  auto_apply_labels: true
  allow_label_editing: true
  labeling_instructions:
    - label: "🗺️ Карты 🗺️"
      instructions: "Применить, когда PR содержит изменения в файлах карт (.yml файлы в папках Resources/Maps/ или Resources/Prototypes/Maps/)"
      
    - label: "🔊 Аудио 🔊"
      instructions: "Применить, когда PR содержит изменения в аудио файлах (.ogg, .mp3, .wav и других звуковых форматах)"
  
    - label: "🧊 Нет C# 🧊"
      instructions: "Применить, когда PR не содержит изменений в .cs файлах"
    
    - label: "🛠️ Есть C# 🛠️"
      instructions: "Применить, когда PR содержит изменения в .cs файлах"
    
    - label: "📚 Изменения: Локализация 📚"
      instructions: "Применить, когда PR содержит изменения в .ftl файлах локализации"
    
    - label: "🖌️ Спрайты 🖌️"
      instructions: "Применить, когда PR содержит изменения в .png, .jpg, .jpeg, .gif или других графических файлах"
    
    - label: "📦 YAML | Прототип 📦"
      instructions: "Применить, когда PR содержит изменения в .yml или .yaml файлах прототипов"
    
    - label: "🔎 На Рассмотрение 🔎"
      instructions: "Применить к новым PR, которые требуют рассмотрения мейнтейнерами"

    - label: "🪟 Интерфейс 🪟"
      instructions: "Применить, когда PR содержит изменения в визуальных элементах интерфейса, которые видны пользователю: кнопки, окна, панели, меню и другие компоненты UI"
      
    - label: "⚖️ Ребаланс ⚖️"
      instructions: "Применить, когда PR явно изменяет игровой баланс: характеристики предметов, урон, скорость, стоимость в прототипах, время действия эффектов. НЕ применять для багфиксов или рефакторинга."
    
    - label: "🤖 ИИ Заготовка 🤖"
      instructions: "Применить ТОЛЬКО если PR был создан полностью ИИ (GitHub Copilot, ChatGPT, Claude и так далее), о чём прямо указано в описании PR, коммитах или очевидно из автогенерированного характера изменений."


chat:
  auto_reply: true

# ═══════════════════════════════════════════════════════════════════════════
# Примечания
# ═══════════════════════════════════════════════════════════════════════════
# 1. Все метки используют emoji для улучшенной визуализации
# 2. Старые текстовые метки исключены из автоматического применения
# 3. CodeRabbit будет применять только релевантные метки на основе содержимого PR
# 4. Метка "Несортированный" полностью исключена из использования
# ═══════════════════════════════════════════════════════════════════════════
