- type: latheRecipe
  id: WeaponEnergyGun
  result: WeaponEnergyGun
  categories:
  - Weapons
  completetime: 8
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: WeaponMiniEnergyGun
  result: WeaponMiniEnergyGun
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 1000
    Glass: 400
    Plastic: 250

- type: latheRecipe
  id: WeaponEnergyGunPistol
  result: WeaponEnergyGunPistol
  categories:
  - Weapons
  completetime: 10
  materials:
    Steel: 1500
    Glass: 600
    Plastic: 400
    Gold: 150

- type: latheRecipe
  id: WeaponGunLaserCarbineAutomatic
  result: WeaponGunLaserCarbineAutomatic
  categories:
  - Weapons
  completetime: 15
  materials:
    Steel: 2000
    Glass: 1000
    Plastic: 500
    Gold: 250
    Silver: 100
    Plasma: 500

- type: latheRecipe
  id: MagazineBatteryLr30
  parent: BaseAmmoRecipe
  result: MagazineBatteryLr30
  materials:
    Steel: 250
    Glass: 50
    Plasma: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleBoxIncendiary
  result: MagazineLightRifleBoxIncendiary
  materials:
    Steel: 150
    Plastic: 475
    Plasma: 475

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  materials:
    Steel: 145

- type: latheRecipe
  id: MagazineLightMachineGunMG60
  result: MagazineLightMachineGunMG60
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 3700

- type: latheRecipe
  id: MagazinePPSH41
  result: MagazinePPSH41
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 1200

- type: latheRecipe
  id: MagazineRPD
  result: MagazineRPD
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 1465

- type: latheRecipe
  id: MagazineLightRifleBox
  result: MagazineLightRifleBoxSP
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 1100

- type: latheRecipe
  id: MagazineNewVector
  result: MagazineNewVector
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 835

- type: latheRecipe
  id: MagazineMP38
  result: MagazineMP38
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 835

- type: latheRecipe
  id: MagazineMP5
  result: MagazineMP5
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 835

- type: latheRecipe
  id: MagazineMP7
  result: MagazineMP7
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 835

- type: latheRecipe
  id: MagazineP90
  result: MagazineP90
  categories:
  - Ammo
  completetime: 10
  materials:
    Steel: 1250
    Plastic: 100

- type: latheRecipe
  id: MagazineScorpion
  result: MagazineScorpion
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 835

- type: latheRecipe
  id: MagazineAK
  result: MagazineAK
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 565

- type: latheRecipe
  id: MagazineRifleHeavySP
  result: MagazineRifleHeavySP
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 500

- type: latheRecipe
  id: MagazineDragunov
  result: MagazineDragunov
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 800

- type: latheRecipe
  id: MagazineV31
  result: MagazineV31
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 985
    Plastic: 600

- type: latheRecipe
  id: MagazineACP14
  result: MagazineACP14
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 250

- type: latheRecipe
  id: MagazineGlock22
  result: MagazineGlock22
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 250

- type: latheRecipe
  id: MagazineVP70
  result: MagazineVP70
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 250

- type: latheRecipe
  id: MagazineHIBrowning
  result: MagazineHIBrowning
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 250

- type: latheRecipe
  id: MagazineDeagle
  result: MagazineDeagle
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 193

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: FlareGunSecurityUpgrade
  result: FlareGunSecurityUpgrade
  categories:
  - Weapons
  materials:
    Plastic: 50
    Steel: 250

- type: latheRecipe
  id: ClothingHeadHelmetPubg
  result: ClothingHeadHelmetPubg
  categories:
  - Weapons
  completetime: 18
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 300

- type: latheRecipe
  id: ClothingShoesBootsMagCombat
  result: ClothingShoesBootsMagCombat
  categories:
  - Weapons
  completetime: 25
  materials:
    Steel: 1200
    Plastic: 500
    Silver: 200

- type: latheRecipe
  id: VestSecUpgrade
  result: VestSecUpgrade
  categories:
  - Weapons
  completetime: 60
  materials:
    Plastic: 1000
    Steel: 500
    Glass: 500
    Plasma: 25

- type: latheRecipe
  id: ModularReceiverAuto
  result: ModularReceiverAuto
  categories:
  - Weapons
  completetime: 10
  materials:
    Steel: 500
    Plastic: 50

- type: latheRecipe
  id: DrozdUpgrade
  result: DrozdUpgrade
  categories:
  - Weapons
  completetime: 16
  materials:
    Steel: 150
    Plastic: 300
    Gold: 50

- type: latheRecipe
  id: LecterUpgrade
  result: LecterUpgrade
  categories:
  - Weapons
  completetime: 16
  materials:
    Steel: 150
    Plastic: 300
    Gold: 50

#
#- type: latheRecipe  # Отдельной технологией
#  id: BaseMagazinePistolCaselessRifleExtended
#  result: BaseMagazinePistolCaselessRifleExtended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 350
#    Plastic: 200
#
#- type: latheRecipe
#  id: MagazinePPSH41Extended
#  result: MagazinePPSH41Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 1200
#
#- type: latheRecipe
#  id: MagazineMP5Extended
#  result: MagazineMP5Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 600
#
#- type: latheRecipe
#  id: MagazineMP7Extended
#  result: MagazineMP7Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 600
#
#- type: latheRecipe
#  id: MagazineRifleExtended
#  result: MagazineRifleExtended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 450
#
#- type: latheRecipe
#  id: MagazineAR18Extended
#  result: MagazineAR18Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 650
#
#- type: latheRecipe
#  id: MagazineM28Extended
#  result: MagazineM28Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 650
#
#- type: latheRecipe
#  id: MagazineV31Extended
#  result: MagazineV31Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 1300
#    Plastic: 100
#
#- type: latheRecipe
#  id: MagazineBauer127Extended
#  result: MagazineBauer127Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 1200
#    Plastic: 50
#
#- type: latheRecipe
#  id: MagazineBR64Extended
#  result: MagazineBR64Extended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 1000
#    Plastic: 50
#
#- type: latheRecipe
#  id: MagazineDragunovExtended
#  result: MagazineDragunovExtended
#  categories:
#  - Weapons
#  completetime: 12
#  materials:
#    Steel: 1200


- type: latheRecipe
  id: EnergyDomeDirectionalTurtle
  result: EnergyDomeDirectionalTurtle
  completetime: 12
  materials:
    Steel: 1000
    Plastic: 500
    Gold: 250
    Uranium: 50

- type: latheRecipe
  id: ShellEMPArtillery
  result: ShellEMPArtillery
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: ShellBlastArtillery
  result: ShellBlastArtillery
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: ShellFlashArtillery
  result: ShellFlashArtillery
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatIon
  result: WeaponMechCombatIon
  categories:
  - MechWeapons
  completetime: 30
  materials:
    Steel: 2500
    Plastic: 1000
    Plasma: 500
    Glass: 500
    Gold: 100

- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 2800
    Plastic: 1000
    Plasma: 750
    Glass: 500

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1650
    Plastic: 300
    Plasma: 250
    Glass: 200

- type: latheRecipe
  id: WeaponMechCombatXray
  result: WeaponMechCombatXray
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 2500
    Glass: 500
    Plastic: 300
    Plasma: 250
    Gold: 100

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1200
    Plastic: 200
    Plasma: 150
    Glass: 50

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1000
    Plastic: 200

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1600
    Plastic: 550

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1500
    Plastic: 800
    Plasma: 300

- type: latheRecipe
  id: WeaponMechCombatMG
  result: WeaponMechCombatMG
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 3000
    Plastic: 500
    Plasma: 100

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 750
    Glass: 250
    Plastic: 300

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 1200
    Glass: 300
    Plastic: 450

- type: latheRecipe
  id: WeaponMechCombatMissileRack8
  result: WeaponMechCombatMissileRack8
  categories:
  - MechWeapons
  completetime: 20
  materials:
    Steel: 2500
    Glass: 1500
    Plastic: 750

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  categories:
  - MechEquipment
  completetime: 20
  materials:
    Steel: 1500
    Glass: 750
    Silver: 150

- type: latheRecipe
  id: MechIndustrialPlasmaCutter
  result: WeaponMechIndustrialPlasmaCutter
  categories:
  - MechEquipment
  completetime: 20
  materials:
    Steel: 1800
    Plasma: 1200
    Glass: 300
    Plastic: 50

# WT550 Sunrise Ammunition
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedSP
  result: MagazinePistolSubMachineGunTopMountedSP
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedRubber
  result: MagazinePistolSubMachineGunTopMountedRubber
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunRubber
  result: MagazinePistolSubMachineGunRubber
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedHP
  result: MagazinePistolSubMachineGunTopMountedHP
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedAP
  result: MagazinePistolSubMachineGunTopMountedAP
  materials:
    Plastic: 150
    Steel: 150
    Uranium: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedPractice
  result: MagazinePistolSubMachineGunTopMountedPractice
  materials:
    Steel: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedIncendiary
  result: MagazinePistolSubMachineGunTopMountedIncendiary
  materials:
    Steel: 25
    Plastic: 135
    Plasma: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedUranium
  result: MagazinePistolSubMachineGunTopMountedUranium
  materials:
    Steel: 25
    Plastic: 250
    Uranium: 250

- type: latheRecipe # Sunrise-Todo: Отдельной дешевой Т2 технологией с зависимостью от Uranium Munitions и Incendiary Ammunition
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolHighCapacityEmpty
  result: MagazinePistolHighCapacityEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityUranium
  result: MagazinePistolHighCapacityUranium
  materials:
    Steel: 25
    Plastic: 125
    Uranium: 125

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityIncendiary
  result: MagazinePistolHighCapacityIncendiary
  materials:
    Steel: 25
    Plastic: 70
    Plasma: 70

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacitySP
  result: MagazinePistolHighCapacitySP
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityHP
  result: MagazinePistolHighCapacityHP
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityFMJ
  result: MagazinePistolHighCapacityFMJ
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityAP
  result: MagazinePistolHighCapacityAP
  materials:
    Plastic: 75
    Steel: 125
    Uranium: 150

# Rubber Ammunition
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolRubber
  result: MagazinePistolRubber
  materials:
    Steel: 25
    Plastic: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityRubber
  result: MagazinePistolHighCapacityRubber
  materials:
    Steel: 30
    Plastic: 70

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumRubber
  result: SpeedLoaderMagnumRubber
  materials:
    Steel: 50
    Plastic: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumRubber
  result: MagazineMagnumRubber
  materials:
    Steel: 25
    Plastic: 60

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  materials:
    Plastic: 120

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  materials:
    Plastic: 300

#Cybernetics
- type: latheRecipe
  id: LeftArmCyberMantisBladeMaxGuard
  result: LeftArmCyberMantisBladeMaxGuard
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: RightArmCyberMantisBladeMaxGuard
  result: RightArmCyberMantisBladeMaxGuard
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100
#
- type: latheRecipe
  id: LeftArmCyberGrenadeThrower
  result: LeftArmCyberGrenadeThrower
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 550
    Steel: 650
    Gold: 100
    Glass: 100

- type: latheRecipe
  id: RightArmCyberGrenadeThrower
  result: RightArmCyberGrenadeThrower
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 550
    Steel: 650
    Gold: 100
    Glass: 100
#
- type: latheRecipe
  id: LeftArmCyberLaserEmitter
  result: LeftArmCyberLaserEmitter
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: RightArmCyberLaserEmitter
  result: RightArmCyberLaserEmitter
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100
#
- type: latheRecipe
  id: LeftArmCyberBulwark
  result: LeftArmCyberBulwark
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: RightArmCyberBulwark
  result: RightArmCyberBulwark
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100
