# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys

- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  #- SunrisePlasma # Прибытие стыкуется лишь 1 доком с доступом командования. Эвак стыкуется лишь 2 доками.
  #- SunriseBox # Прибытие не стыкуется, эвак стыкуется лишь 1 доком.
  #- SunriseBarratry # Прибытие не стыкуется. Эвак залазит в станцию.
  - SunriseFland #Fish-edit
  - SunrisePacked #Fish-edit
  #- SunriseMarathon # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseBagel # Прибытие стыкуется но не туда. Эвак залазит в станцию.
  #- SunriseOasis # Прибытие не стыкуется. Эвак залазит в станцию.
  # НЕИГРАБЕЛЬНЫЕ:
  #- SunriseReach
  #- SunriseRelic
  # SUNRISE-TODO: Старые-новые карты
  #- Glacier
  #- Shoukou
  #- Hammurabi
  #- Lighthouse
  #- Angle
  #- Pebble
  #- Ovni
  #- Kettle
  #- Tortuga
  #- Arena
