- type: roleLoadout
  id: LustSunriseJobHeadOfPersonnel
  groups:
  - HoPHead
  - SunriseGlasses
  - LustHoPNeck
  - HoPJumpsuit
  - HoPOuterClothing
  - GroupTankHarness
  - HoPBackpack
  - SunriseSurvival
  - SunriseGroupSpeciesBreathTool
  - SunriseHoPBra
  - SunriseHoPPants
  - Socks
  - SunriseTrinkets
  - HoPJobTrinkets
  - SpecialLoadout
  - Contributors

