- type: entity
  parent: ClothingUniformJumpsuitPrisonRegularBase
  id: ClothingUniformJumpsuitPrisonTrainee
  name: prison trainee jumpsuit
  description: Freshly issued uniform with crisp lines and minimal wear, representing the first steps into a world where authority must be earned through vigilance and steel.
  components:
  - type: Sprite
    layers:
    - state: icon
    - state: overlay-icon
      color: "#ff8c00"
  - type: Item
    inhandVisuals:
      left:
      - state: inhand-left
      - state: overlay-inhand-left
        color: "#ff8c00"
      right:
      - state: inhand-right
      - state: overlay-inhand-right
        color: "#ff8c00"
  - type: Clothing
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING
      - state: overlay-equipped
        color: "#ff8c00"

- type: entity
  parent: ClothingUniformJumpsuitPrisonVeteranBase
  id: ClothingUniformJumpsuitPrisonTraineeVeteran
  name: veteran prison trainee jumpsuit
  description: Seasoned training uniform for experienced mentors who have guided countless recruits through their first challenging days, their wisdom earned through years of shaping the next generation of guards.
  components:
  - type: Sprite
    layers:
    - state: icon
    - state: overlay-icon
      color: "#ff8c00"
  - type: Item
    inhandVisuals:
      left:
      - state: inhand-left
      - state: overlay-inhand-left
        color: "#ff8c00"
      right:
      - state: inhand-right
      - state: overlay-inhand-right
        color: "#ff8c00"
  - type: Clothing
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING
      - state: overlay-equipped
        color: "#ff8c00"
