using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Content.Shared._Sunrise.ERP;
using Robust.Client.GameObjects;
using Content.Shared.Humanoid;
using Robust.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Robust.Client.Player;
using Robust.Shared.Prototypes;
using Robust.Client.Graphics;
using Robust.Shared.Timing;
namespace Content.Client._Sunrise.ERP;

[GenerateTypedNameReferences]
public sealed partial class InteractionWindow : DefaultWindow
{
    private readonly SpriteSystem _spriteSystem;
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    public NetEntity? TargetEntityId { get; set; }
    public Sex? UserSex { get; set; }
    public Sex? TargetSex { get; set; }
    public bool UserHasClothing { get; set; }
    public bool TargetHasClothing { get; set; }
    public bool Erp { get; set; }
    public ProgressBar LoveBar;
    public TimeSpan TimeUntilAllow = TimeSpan.Zero;
    private readonly InteractionEui _eui;
    public TimeSpan UntilUpdate = TimeSpan.Zero;
    public InteractionWindow(InteractionEui eui)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _eui = eui;
        LoveBar = ProgressBar;
        SearchBar.OnTextChanged += SearchBarOnOnTextChanged;
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat(backgroundColor: Color.Pink);
    }

    private void SearchBarOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        PopulateByFilter(SearchBar.Text);
    }

    private void PopulateByFilter(string filter)
    {
        ItemInteractions.Clear();
        foreach (var proto in _prototypeManager.EnumeratePrototypes<InteractionPrototype>())
        {
            if (string.IsNullOrEmpty(filter) ||
                proto.Name.ToLowerInvariant().Contains(filter.Trim().ToLowerInvariant()))
            {
                var texture = _spriteSystem.Frame0(proto.Icon);
                if (UserHasClothing && proto.UserWithoutCloth) continue;
                if (TargetHasClothing && proto.TargetWithoutCloth) continue;
                if (UserSex != proto.UserSex && proto.UserSex != Sex.Unsexed) continue;
                if (TargetSex != proto.TargetSex && proto.TargetSex != Sex.Unsexed) continue;
                if (!Erp && proto.Erp) continue;
                ItemInteractions.AddItem(proto.Name, texture, metadata: proto);
            }
        }
    }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if(_gameTiming.CurTime > UntilUpdate)
        {
            UntilUpdate = _gameTiming.CurTime + TimeSpan.FromMicroseconds(4);
            _eui.RequestLove();
        }
    }


        public void Populate(List<InteractionPrototype> prototypes)
    {
        //Проверки nullable-типов
        if (!TargetEntityId.HasValue) return;
        if (!UserSex.HasValue) return;
        if (!TargetSex.HasValue) return;
        if (!_player.LocalEntity.HasValue) return;

        //Аминь
        if (Erp)
        {
            //Юзер
            UserDescription.AddChild(new Label {Text = "Вы..."});
            if (UserHasClothing) UserDescription.AddChild(new Label { Text = "...Обладаете одеждой" });
            else UserDescription.AddChild(new Label { Text = "...Не обладаете одеждой" });
            if (UserSex.Value == Sex.Male) UserDescription.AddChild(new Label { Text = "...Обладаете пенисом" });
            else if (UserSex.Value == Sex.Female) UserDescription.AddChild(new Label { Text = "...Обладаете вагиной" });
            //Таргет
            TargetDescription.AddChild(new Label { Text = Identity.Name(_eui._entManager.GetEntity(TargetEntityId.Value), _eui._entManager, _player.LocalEntity.Value) + "..." });
            if (TargetHasClothing) TargetDescription.AddChild(new Label { Text = "...Обладает одеждой" });
            else TargetDescription.AddChild(new Label { Text = "...Не обладает одеждой" });
            if (TargetSex.Value == Sex.Male) TargetDescription.AddChild(new Label { Text = "...Обладает пенисом" });
            else if (TargetSex.Value == Sex.Female) TargetDescription.AddChild(new Label { Text = "...Обладает вагиной" });
        } else
        {
            ErpProgress.Dispose();
        }

        foreach (var proto in prototypes)
        {
            var texture = _spriteSystem.Frame0(proto.Icon);
            if (UserHasClothing && proto.UserWithoutCloth) continue;
            if (TargetHasClothing && proto.TargetWithoutCloth) continue; 
            if (UserSex != proto.UserSex && proto.UserSex != Sex.Unsexed) continue;
            if (TargetSex != proto.TargetSex && proto.TargetSex != Sex.Unsexed) continue;
            if (!Erp && proto.Erp) continue;
            ItemInteractions.AddItem(proto.Name, texture, metadata: proto);
        }
        ItemInteractions.OnItemSelected += _eui.OnItemSelect;
    }
}
