- type: roleLoadout
  id: LustSunriseJobCargoTechnician
  groups:
  - SunriseCargoTechnicianHead
  - SunriseGlasses
  - SunriseCargoTechMask
  - SunriseCargoTechNeck
  - CargoTechnicianJumpsuit
  - SunriseCargoTechnicianOuterClothing
  - SunriseCargoTechGloves
  - SunriseCargoTechnicianShoes
  - GroupTankHarness
  - CargoTechnicianBackpack
  - CargoTechnicianID
  - SunriseSurvival
  - GroupSpeciesBreathTool
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - CargoTechnicianJobTrinkets
  - TrinketsCargo
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustSunriseJobSalvageSpecialist
  groups:
  - SunriseSalvageHead
  - SunriseGlasses
  - SunriseSalvageMask
  - LustSalvageSpecialistNeck
  - SunriseSalvageSpecialistOuterClothing
  - SunriseSalvageGloves
  - SunriseSalvageSpecialistShoes
  - GroupTankHarness
  - SalvageSpecialistBackpack
  - SunriseSurvival
  - GroupSpeciesBreathTool
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - SalvageSpecialistJobTrinkets
  - TrinketsCargo
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustJobMailCarrier
  groups:
  - SunriseCargoTechNeck
  - MailCarrierJumpsuit
  - SunriseCargoTechGloves
  - CargoTechnicianBackpack
  - GroupTankHarness
  - SunriseSurvival
  - GroupSpeciesBreathTool
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - TrinketsCargo
  - SpecialLoadout
  - Contributors

- type: roleLoadout
  id: LustJobMiningSpecialist
  groups:
  - SunriseSalvageHead
  - SunriseGlasses
  - SunriseSalvageMask
  - LustSalvageSpecialistNeck
  - SunriseSalvageSpecialistOuterClothing
  - SunriseSalvageGloves
  - SunriseSalvageSpecialistShoes
  - SalvageSpecialistBackpack
  - GroupTankHarness
  - SunriseSurvival
  - GroupSpeciesBreathTool
  - Bra
  - Pants
  - Socks
  - SunriseTrinkets
  - TrinketsCargo
  - SpecialLoadout
  - Contributors

