// Hand "pick a card" picker. Adapted from the original radial menu to a simple
// windowed grid because lust-station has no RadialMenuTextureButton control.
using System.Numerics;
using Content.Shared._Lust.Cards.Card;
using Content.Shared._Lust.Cards.Stack;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._Lust.Cards.Hand.UI;

[GenerateTypedNameReferences]
public sealed partial class CardHandMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public event Action<NetEntity>? OnCardSelected;

    public CardHandMenu(EntityUid owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        if (!_entManager.TryGetComponent<CardStackComponent>(owner, out var stack))
            return;

        foreach (var card in stack.Cards)
        {
            if (!_entManager.TryGetComponent<CardComponent>(card, out var cardComp))
                continue;

            string cardName;
            if (cardComp.Flipped && _entManager.TryGetComponent<MetaDataComponent>(card, out var meta))
                cardName = meta.EntityName;
            else
                cardName = Loc.GetString(cardComp.Name);

            var spriteView = new SpriteView
            {
                Scale = new Vector2(2f, 2f),
            };
            spriteView.SetEntity(card);

            var button = new ContainerButton
            {
                ToolTip = cardName,
            };
            button.AddChild(spriteView);

            var net = _entManager.GetNetEntity(card);
            button.OnPressed += _ =>
            {
                OnCardSelected?.Invoke(net);
                Close();
            };

            CardGrid.AddChild(button);
        }
    }
}
