# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys

- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  #- SunriseBox
#  - SunrisePlasma # НЕ ГОТОВО ПРИБЫТИЕ/ОТБЫТИЕ ДЛЯ БОЛЬШОГО ШАТТЛА
  #- SunriseBarratry
  #- SunriseFland
  #- SunriseMarathon
  #- SunriseBagel
  #- SunrisePacked
  #- SunriseOasis
  # НЕИГРАБЕЛЬНЫЕ:
  #- SunriseReach
  #- SunriseRelic
  # SUNRISE-TODO: Старые-новые карты
  #- Glacier
  #- Shoukou
  #- Hammurabi
  #- Lighthouse
  #- Angle
  #- Pebble
  #- Ovni
  #- Kettle
  #- Tortuga
  #- Arena
